### ISSUE TITLE
Wont Display Monitoring UI

### ISSUE THREAD

**Issue by GameDevCatch** [JohnBaracuda/Runtime-Monitoring#13]
I've tried opening the example scene and just get errors stopping it from displaying it seems.
Also tried a default scene with just a script that is a monitored Behavior using the Monitor attributes and still doesn't display on play. Also, when in the example scene and pressing the open Monitor Display key in play mode it just gives a null reference exception.

![Capture](https://user-images.githubusercontent.com/63822144/196992058-e6833925-b90c-4113-a1ab-5e14c70b69d6.PNG)

**Comment by JohnBaracuda** [comment]
Hey, sorry for the inconvinience. I was unable to reproduce the issue in multiple projects but found some other isses related to async profiling / execution order, that I am working on right now. An update is coming soon. 

Since I don't know if what I found is actually related to your issue, some additional information would be very helpful.

• What Unity version are you using.
• What is your target platform.
• Did you upgrade the asset from an older version and if yes which one.
• Can you show me the full stacktrace of the exception.
• Can you show or tell me what your active monitoring settings are (General & UI Controller -settings)

**Comment by GameDevCatch** [comment]
Hi, I'm using version 2021.3.1f1 however after doing a clean install in a new project it works with zero errors now the only problem, I encountered is there's no black boxes behind the Monitoring UI when "Enter Play Mode Options" is enabled in settings. other than that, it works perfectly now.

![Capture](https://user-images.githubusercontent.com/63822144/197045095-dd2ee2b5-260a-453c-827d-4fef949bb27b.PNG)

**Comment by JohnBaracuda** [comment]
Yeah it looks like there is an issue with the passed background texture. (There is a warning in your console)
I wold recommend to import one of the UI controller (preferably TMP or UI Toolit) from the samples and use it instead. This should bypass the issue.

After importing the UI Resources you can override the default UI controller by dragging it into the `Monitoring UI Override` field in the settings like this.

![image](https://user-images.githubusercontent.com/58704151/197053319-01ce2159-7fc3-4773-b496-88e6b9a14a0d.png)

**Comment by GameDevCatch** [comment]
Thanks for the fast support!
