### ISSUE TITLE
Uninstall ?

### ISSUE THREAD

**Issue by chriztheanvill** [JohnBaracuda/Runtime-Monitoring#7]
Hi.
How to uninstall this plugin? I've tried to remove the folder Barracuda but shows this message.

```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Graphs.Edge.WakeUp () (at /home/bokken/buildslave/unity/build/Editor/Graphs/UnityEditor.Graphs/Edge.cs:114)
UnityEditor.Graphs.Graph.DoWakeUpEdges (System.Collections.Generic.List`1[T] inEdges, System.Collections.Generic.List`1[T] ok, System.Collections.Generic.List`1[T] error, System.Boolean inEdgesUsedToBeValid) (at /home/bokken/buildslave/unity/build/Editor/Graphs/UnityEditor.Graphs/Graph.cs:387)
UnityEditor.Graphs.Graph.WakeUpEdges (System.Boolean clearSlotEdges) (at /home/bokken/buildslave/unity/build/Editor/Graphs/UnityEditor.Graphs/Graph.cs:286)
UnityEditor.Graphs.Graph.WakeUp (System.Boolean force) (at /home/bokken/buildslave/unity/build/Editor/Graphs/UnityEditor.Graphs/Graph.cs:272)
UnityEditor.Graphs.Graph.WakeUp () (at /home/bokken/buildslave/unity/build/Editor/Graphs/UnityEditor.Graphs/Graph.cs:250)
UnityEditor.Graphs.Graph.OnEnable () (at /home/bokken/buildslave/unity/build/Editor/Graphs/UnityEditor.Graphs/Graph.cs:245)
```

**Comment by JohnBaracuda** [comment]
Hey,
this is a Unity bug, coming from Unity's code in UnityEditor.Graphs.DLL. Looking at similar issues online, a simple editor restart could be a quick fix. If the error persists I would need some more information about your OS, Unity version, plugin version and maybe other plugins/assets installed, but since the origin is not the plugin but Unity I can't guarantee that I'll be able to help.

In general there shouldn't be any more to it then deleting the folder as you did but in this case it looks like unity is holding on to some reference and not properly validation if it still exists. 

I hope this helps :)
